stories = {
    "US01": "ERROR: {story}: INDI/FAM {id}: Date {dateType} {date} occurs after current date {currentDate}",
    "US02": "ERROR: {story}: INDI/FAM {id}: Marriage date: {mDate} occurs before the individual's birthdate {bDate}",
    "US03": "ERROR: {story}: INDI/FAM {id}: Death date: {dDate} occurs before the individual's birthdate {bDate}",
    "US04": "ERROR: {story}: FAM {id}: Divorce date {dDate} occurs before marriage date {mDate}",
    "US05": "ERROR: {story}: FAM {id}: Marriage date {mDate} occurs after death of INDI {indiId}",
    "US06": "ERROR: {story}: FAM {id}: Divorce date {dDate} occurs before death of one or both spouses",
    "US07": "ANOMALY: {story}: INDI {id}: Age over 150 years old: {age}",
    "US08": "ANOMALY: {story}: INDI {id}: Birth date {bDate} occurs before parents' marriage date {mDate} or more than 9 months after parents' divorce date {dDate} in FAM {famID}",
    "US09": "ANOMALY: {story}: INDI {id}: Birth date {bDate} occurs after mother's death {mDeath} or more than 9 months after father's death {dDeath}",
    "US10": "ANOMALY: {story}: INDI {id}: Marriage date: {date} occurs before age of 14",
    "US11": "ANOMALY: {story}: INDI {id} is an active spouse in muliple families. FAMS: {fams}",
    "US12": "ANOMALY: {story}: INDI {id}: Birthdate {bDate} occurs more than {ageLimit} years after {parentString}'s birthday: {parentBirthdate}",
    "US13": "",
    "US14": "",
    "US15": "",
    "US16": "",
    "US17": "",
    "US18": "",
    "US19": "",
    "US20": "",
    "US21": "",
    "US22": "",
    "US23": "",
    "US24": ""
}