stories = {
    "US01": "ERROR: {story}: INDI/FAM {id}: Date {dateType} {date} occurs after current date {currentDate}",
    "US02": "ANNOMALY: {story}: INDI/FAM {id}: Marriage date: {mDate} occurs before the individual's birthdate {bDate}",
    "US03": "ERROR: {story}: INDI/FAM {id}: Death date: {dDate} occurs before the individual's birthdate {bDate}",
    "US04": "ERROR: {story}: FAM {id}: Divorce date {dDate} occurs before marriage date {mDate}",
    "US05": "ERROR: {story}: FAM {id}: Marriage date {mDate} occurs after death of one or both spouses",
    "US06": "ERROR: {story}: FAM {id}: Divorce date {dDate} occurs before death of one or both spouses",
    "US07": "",
    "US08": "",
    "US09": "",
    "US10": "",
    "US11": "ANOMALY: {story}: INDI {id} is an active spouse in muliple families. FAMS: {fams}",
    "US12": "",
    "US13": "",
    "US14": "",
    "US15": "",
    "US16": "",
    "US17": "",
    "US18": "",
    "US19": "",
    "US20": "",
    "US21": "",
    "US22": "",
    "US23": "",
    "US24": "",
    "US25": "",
    "US26": "",
    "US27": "",
    "US28": "",
    "US29": "",
    "US30": "",
    "US31": "",
    "US32": "",
    "US33": "",
    "US34": "",
    "US35": "",
    "US36": "",
    "US37": "",
    "US38": "",
    "US39": "",
    "US40": "",
    "US41": "",
    "US42": ""
}